# Graphiti MCP Server Free Configuration (local-only, no API keys)

[server]
host = "0.0.0.0"
port = 8091
log_level = "info"
require_auth = false
allowed_origins = ["*"]

[cozo]
# Use in-memory for zero-setup; switch to rocksdb/sqlite for persistence
engine = "mem"
path = ""
options = {}

[llm]
provider = "ollama"
model = "disabled"

[embedder]
provider = "embed_anything"
model = "Qwen/Qwen3-Embedding-0.6B"
dimension = 1024
batch_size = 32
timeout = 120
api_key = ""
device = "auto"
max_length = 8192
# 指定本地模型缓存目录（离线可用）
cache_dir = "./.graphiti/models/Qwen3-Embedding-0.6B"

[graphiti]
name = "free"
enable_deduplication = true
min_entity_confidence = 0.6
min_relationship_confidence = 0.5
max_context_window = 4000
generate_embeddings = true
skip_entity_extraction = true

[storage]
search_index_path = "./.graphiti/data/search"
vector_index_path = "./.graphiti/data/vectors"
