# 规范化配置样例（AppConfig 等价数据）
# 注意：字段涵盖 graphiti-core/src/config.rs 中的 AppConfig 及其子结构默认值；
# 此样例用于 TOML/YAML/JSON 三种格式的一致性测试。

[database]
url = "sqlite://graphiti.db"
max_connections = 10
connection_timeout = 30
query_timeout = 60
enable_pooling = true

[llm]
provider = "openai"
api_key = ""
model = "gpt-4"
endpoint = ""
timeout = 30
max_retries = 3
rate_limit = 60

[embedding]
provider = "openai"
api_key = ""
model = "text-embedding-ada-002"
dimensions = 1536
batch_size = 100
timeout = 30

[server]
host = "0.0.0.0"
port = 8080
tls = false
cert_path = ""
key_path = ""
request_timeout = 30
max_body_size = 10485760

log_level = "info"
enable_metrics = true
metrics_port = 9090

